storage: ./storage
plugins: ./plugins

web:
  title: Verdaccio

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@dynamic-labs/*':
    access: $all
    publish: $anonymous
    unpublish: $anonymous
    proxy: npmjs
  '@dynamic-labs-connectors/*':
    access: $all
    publish: $anonymous
    unpublish: $anonymous
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs


server:
  keepAliveTimeout: 60










middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: http }