name: Bump Version
description: Bumps the version of the project and opens a PR
inputs:
  version: # determines what node version to install
    required: false
    description: node js version
    default: 20
  preId:
    description: The prerelease name (Only required if using a bump starting with `pre`)
    default: alpha
  bump:
    description: Increment a version by the specified level
    type: choice
    default: prerelease
    options:
      - major
      - minor
      - patch
      - premajor
      - preminor
      - prepatch
outputs:
  version:
    value: ${{ steps.bumpversion.outputs.version}}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: dynamic-labs/sdk/.github/actions/setup-node@main
      with:
        version: ${{inputs.version}}
    - name: Set git identity
      shell: bash
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Bump Version
      shell: bash
      id: bumpversion
      run: |-
        pnpm release:bump-version -- --version ${{ github.event.inputs.bump }} --preId ${{ github.event.inputs.preId }} --dryRun=false


