name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or commit to publish. The ref must be a chore(release) commit
        default: main

permissions:
  contents: write
  actions: read
  deployments: write
  packages: write

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        env:
          ACTIONS_RUNNER_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        uses: dynamic-labs/sdk/.github/actions/release@main
        with:
          type: publish
          ref: ${{ github.event.inputs.ref }}
