name: Publish Packages

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or commit to publish. The ref must be a chore(release) commit
        default: main
  push:
    branches:
      - main
      - v*

permissions:
  contents: write
  actions: read
  deployments: write

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.commits.message, 'chore(bump-version): bump package versions') }}"
    steps:
      - name: Checkout ${{ github.event.inputs.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0
      - name: Publish
        env:
          ACTIONS_RUNNER_DEBUG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        uses: dynamic-labs/sdk/.github/actions/release@main
        with:
          type: publish